### ISSUE TITLE
Analisar o relatório relativo a hospedagem

### ISSUE THREAD

**Issue by filipeandrev** [jhonnyfreitas1/COMDICA#8]

**Comment by allan-diego** [comment]
Verificar as seguintes pendências no documento:

- Bullet está com um 10 no lugar da bola completamente preta;

- Sugestão de mudança para o parágrafo da justificativa:

O motivo da escolha pela hospedagem se deu devido a sua confiabilidade, bem
como seus componentes de qualidade. Estes são mais que suficientes para
atender à todas as necessidades para implementação do site, possuindo
características como banda larga, composer, banco de dados e outros atributos
já citados por um custo consideravelmente razoável. Assim, esse conjunto de
características foram os determinantes para a escolha do **plano XXXX** do **Provedor de Hospedagem YYYYY**.

- Dar um espaço antes no título "Preços - Local Web"
